--MEMBER 테이블
insert into member (idx, id, password, name, gender, dateofbirthday, email, phone) values (member_idx_seq.nextval, 'hong', '1111', '홍길동', '남자', '19930716', 'hong@naver.com', '01088179307');
insert into member (idx, id, password, name, gender, dateofbirthday, email, phone) values (member_idx_seq.nextval, 'lim', '2222', '임꺽정', '여자', '19950419', 'lim@gmail.com', '01026811007');
insert into member (idx, id, password, name, gender, dateofbirthday, email, phone) values (member_idx_seq.nextval, 'jang', '3333', '장길산', '남자', '19900127', 'jang@nate.com', '01033333333');
insert into member (idx, id, password, name, gender, dateofbirthday, email, phone) values (member_idx_seq.nextval, 'li123', '4444', '일지매', '여자', '19910111', 'il123@gmail.com', '01044444444');
insert into member (idx, id, password, name, gender, dateofbirthday, email, phone) values (member_idx_seq.nextval, 'sonheungmin', '5555', '손흥민', '남자', '19920708', 'sontot@gmail.com', '01055555555');
insert into member (idx, id, password, name, gender, dateofbirthday, email, phone) values (member_idx_seq.nextval, 'park', '6666', '박용택', '남자', '19800202', 'yongtaek', '010666666666');
insert into member (idx, id, password, name, gender, dateofbirthday, email, phone) values (member_idx_seq.nextval, 'seojanghoon', '7777', '서장훈', '남자', '19780925', 'seo@gmail.com', '01077777777');
insert into member (idx, id, password, name, gender, dateofbirthday, email, phone) values (member_idx_seq.nextval, 'gpark', '8888', '박명수', '남자', '19920708', 'gpark@gmail.com', '01088888888');
insert into member (idx, id, password, name, gender, dateofbirthday, email, phone) values (member_idx_seq.nextval, 'maeddugi', '9999', '유재석', '남자', '19920708', 'youjaesuk@gmail.com', '01099999999');
insert into member (idx, id, password, name, gender, dateofbirthday, email, phone) values (member_idx_seq.nextval, 'gang', '0000', '강호동', '남자', '19920708', 'hodong@gmail.com', '01012341234');
insert into member (idx, id, password, name, gender, dateofbirthday, email, phone) values (member_idx_seq.nextval, 'jessi', '1111', '제시', '여', '19920507', 'jessisexy@gmail.com', '01023452345');
insert into member (idx, id, password, name, gender, dateofbirthday, email, phone) values (member_idx_seq.nextval, 'harrykane','1212', '해리케인', '남자', '19920728', 'kandgod@gmail.com', '01074567777');

--INTERLIST 테이블
insert into interlist (interidx, id, interests) values (interlist_interidx_seq.nextval, 'hong', '사회');
insert into interlist (interidx, id, interests) values (interlist_interidx_seq.nextval, 'hong', '연예');
insert into interlist (interidx, id, interests) values (interlist_interidx_seq.nextval, 'hong', '스포츠');
insert into interlist (interidx, id, interests) values (interlist_interidx_seq.nextval, 'hong', 'IT');
insert into interlist (interidx, id, interests) values (interlist_interidx_seq.nextval, 'hong', '게임');
insert into interlist (interidx, id, interests) values (interlist_interidx_seq.nextval, 'hong', '쇼핑');
insert into interlist (interidx, id, interests) values (interlist_interidx_seq.nextval, 'lim', '사회');
insert into interlist (interidx, id, interests) values (interlist_interidx_seq.nextval, 'lim', '연예');
insert into interlist (interidx, id, interests) values (interlist_interidx_seq.nextval, 'lim', '스포츠');
insert into interlist (interidx, id, interests) values (interlist_interidx_seq.nextval, 'lim', 'IT');
insert into interlist (interidx, id, interests) values (interlist_interidx_seq.nextval, 'lim', '게임');
insert into interlist (interidx, id, interests) values (interlist_interidx_seq.nextval, 'lim', '쇼핑');
insert into interlist (interidx, id, interests) values (interlist_interidx_seq.nextval, 'jang', '사회');
insert into interlist (interidx, id, interests) values (interlist_interidx_seq.nextval, 'jang', '연예');
insert into interlist (interidx, id, interests) values (interlist_interidx_seq.nextval, 'jang', '스포츠');
insert into interlist (interidx, id, interests) values (interlist_interidx_seq.nextval, 'jang', 'IT');
insert into interlist (interidx, id, interests) values (interlist_interidx_seq.nextval, 'jang', '게임');
insert into interlist (interidx, id, interests) values (interlist_interidx_seq.nextval, 'jang', '쇼핑');
insert into interlist (interidx, id, interests) values (interlist_interidx_seq.nextval, 'li123', '사회');
insert into interlist (interidx, id, interests) values (interlist_interidx_seq.nextval, 'li123', '연예');
insert into interlist (interidx, id, interests) values (interlist_interidx_seq.nextval, 'li123', '스포츠');
insert into interlist (interidx, id, interests) values (interlist_interidx_seq.nextval, 'li123', 'IT');
insert into interlist (interidx, id, interests) values (interlist_interidx_seq.nextval, 'li123', '게임');
insert into interlist (interidx, id, interests) values (interlist_interidx_seq.nextval, 'li123', '쇼핑');
insert into interlist (interidx, id, interests) values (interlist_interidx_seq.nextval, 'sonheungmin', '사회');
insert into interlist (interidx, id, interests) values (interlist_interidx_seq.nextval, 'sonheungmin', '연예');
insert into interlist (interidx, id, interests) values (interlist_interidx_seq.nextval, 'sonheungmin', '스포츠');
insert into interlist (interidx, id, interests) values (interlist_interidx_seq.nextval, 'sonheungmin', 'IT');
insert into interlist (interidx, id, interests) values (interlist_interidx_seq.nextval, 'sonheungmin', '게임');
insert into interlist (interidx, id, interests) values (interlist_interidx_seq.nextval, 'sonheungmin', '쇼핑');
insert into interlist (interidx, id, interests) values (interlist_interidx_seq.nextval, 'park', '사회');
insert into interlist (interidx, id, interests) values (interlist_interidx_seq.nextval, 'park', '연예');
insert into interlist (interidx, id, interests) values (interlist_interidx_seq.nextval, 'park', '스포츠');
insert into interlist (interidx, id, interests) values (interlist_interidx_seq.nextval, 'park', 'IT');
insert into interlist (interidx, id, interests) values (interlist_interidx_seq.nextval, 'park', '게임');
insert into interlist (interidx, id, interests) values (interlist_interidx_seq.nextval, 'park', '쇼핑');
insert into interlist (interidx, id, interests) values (interlist_interidx_seq.nextval, 'seojanghoon', '사회');
insert into interlist (interidx, id, interests) values (interlist_interidx_seq.nextval, 'seojanghoon', '연예');
insert into interlist (interidx, id, interests) values (interlist_interidx_seq.nextval, 'seojanghoon', '스포츠');
insert into interlist (interidx, id, interests) values (interlist_interidx_seq.nextval, 'seojanghoon', 'IT');
insert into interlist (interidx, id, interests) values (interlist_interidx_seq.nextval, 'seojanghoon', '게임');
insert into interlist (interidx, id, interests) values (interlist_interidx_seq.nextval, 'seojanghoon', '쇼핑');
insert into interlist (interidx, id, interests) values (interlist_interidx_seq.nextval, 'gpark', '사회');
insert into interlist (interidx, id, interests) values (interlist_interidx_seq.nextval, 'gpark', '연예');
insert into interlist (interidx, id, interests) values (interlist_interidx_seq.nextval, 'gpark', '스포츠');
insert into interlist (interidx, id, interests) values (interlist_interidx_seq.nextval, 'gpark', 'IT');
insert into interlist (interidx, id, interests) values (interlist_interidx_seq.nextval, 'gpark', '게임');
insert into interlist (interidx, id, interests) values (interlist_interidx_seq.nextval, 'gpark', '쇼핑');
insert into interlist (interidx, id, interests) values (interlist_interidx_seq.nextval, 'maeddugi', '사회');
insert into interlist (interidx, id, interests) values (interlist_interidx_seq.nextval, 'maeddugi', '연예');
insert into interlist (interidx, id, interests) values (interlist_interidx_seq.nextval, 'maeddugi', '스포츠');
insert into interlist (interidx, id, interests) values (interlist_interidx_seq.nextval, 'maeddugi', 'IT');
insert into interlist (interidx, id, interests) values (interlist_interidx_seq.nextval, 'maeddugi', '게임');
insert into interlist (interidx, id, interests) values (interlist_interidx_seq.nextval, 'maeddugi', '쇼핑');
insert into interlist (interidx, id, interests) values (interlist_interidx_seq.nextval, 'gang', '사회');
insert into interlist (interidx, id, interests) values (interlist_interidx_seq.nextval, 'gang', '연예');
insert into interlist (interidx, id, interests) values (interlist_interidx_seq.nextval, 'gang', '스포츠');
insert into interlist (interidx, id, interests) values (interlist_interidx_seq.nextval, 'gang', 'IT');
insert into interlist (interidx, id, interests) values (interlist_interidx_seq.nextval, 'gang', '게임');
insert into interlist (interidx, id, interests) values (interlist_interidx_seq.nextval, 'gang', '쇼핑');
insert into interlist (interidx, id, interests) values (interlist_interidx_seq.nextval, 'jessi', '사회');
insert into interlist (interidx, id, interests) values (interlist_interidx_seq.nextval, 'jessi', '연예');
insert into interlist (interidx, id, interests) values (interlist_interidx_seq.nextval, 'jessi', '스포츠');
insert into interlist (interidx, id, interests) values (interlist_interidx_seq.nextval, 'jessi', 'IT');
insert into interlist (interidx, id, interests) values (interlist_interidx_seq.nextval, 'jessi', '게임');
insert into interlist (interidx, id, interests) values (interlist_interidx_seq.nextval, 'jessi', '쇼핑');
insert into interlist (interidx, id, interests) values (interlist_interidx_seq.nextval, 'harrykane', '사회');
insert into interlist (interidx, id, interests) values (interlist_interidx_seq.nextval, 'harrykane', '연예');
insert into interlist (interidx, id, interests) values (interlist_interidx_seq.nextval, 'harrykane', '스포츠');
insert into interlist (interidx, id, interests) values (interlist_interidx_seq.nextval, 'harrykane', 'IT');
insert into interlist (interidx, id, interests) values (interlist_interidx_seq.nextval, 'harrykane', '게임');
insert into interlist (interidx, id, interests) values (interlist_interidx_seq.nextval, 'harrykane', '쇼핑');

--BOARD 테이블
insert into board (bidx, name, category, ref, subject, content, hit, replycnt) values (board_bidx_seq.nextval, '홍길동', '사회', '1', '코로나', '너무 싫어요', 0, 0);